#!/usr/bin/env python3
"""
Every launcher and store icon of the app, from one definition of the glyph.

The glyph is design 3a ("Mapa teal") from the Claude Design file "App Icon.dc.html", chosen by the
owner on 2026-10-06: the AdventureLog backend's folded map, redrawn flat in this client's teal - a
white map in three panels with light-cyan continents, the middle panel one tone down. The numbers
below are the design's own SVG layers (assets/icon-svg/3a-*.svg in the export). Change them here and
run this script; nothing it writes is meant to be edited by hand.

    python3 scripts/icon/generate_icon.py

Writes:
  - Android adaptive icon: drawable-v24/ic_launcher_foreground.xml, drawable/ic_launcher_background.xml,
    drawable/ic_launcher_monochrome.xml (themed icons, Android 13+) and the two mipmap-anydpi-v26 XMLs
  - Android legacy PNGs (Android 7.x has no adaptive icons): mipmap-*/ic_launcher(_round).png
  - iOS: iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png, without alpha (the App
    Store refuses an icon with an alpha channel)
  - Play Store: docs/icon-512.png

PNGs are rendered with macOS Quick Look (qlmanage, WebKit) and sized with sips: no extra installs.
"""
import os
import shutil
import subprocess
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RES = os.path.join(ROOT, "composeApp", "src", "androidMain", "res")

GRADIENT = ("#007A85", "#005A62")   # the tile, top to bottom, slightly tilted (x 0.37 -> 0.63)
PAPER = "#FFFFFF"
LAND = "#7FD3DB"
FOLD = ("#00373E", 0.16)            # the middle panel, one tone down

# --- The glyph, in the design's 100 x 100 box -----------------------------------------------------

MAP = "M16,28 L38,19 L62,28 L84,19 L84,74 L62,83 L38,74 L16,83 Z"
CONTINENTS = [
    "M8,20 C28,18 35,30 31,40 C27,48 18,52 8,55 Z",
    "M45,43 C50,35 61,39 59,47 C65,52 61,63 52,63 C44,63 43,55 48,51 C44,51 42,48 45,43 Z",
    "M70,8 L92,8 L92,30 C82,42 73,45 70,38 C67,30 75,24 70,8 Z",
    "M18,92 C22,77 34,70 44,74 C54,76 59,81 55,92 Z",
    "M92,60 C81,60 74,66 76,72 C72,77 72,86 80,86 L92,86 Z",
]
MIDDLE_PANEL = "M38,19 L62,28 L62,83 L38,74 Z"
# The monochrome layer is the map's three panels, the middle one at 60%: themed icons keep only
# the alpha, so the fold still reads without the colours.
MONO_PANELS = [("M16,28 L38,19 L38,74 L16,83 Z", 1.0), (MIDDLE_PANEL, 0.6), ("M62,28 L84,19 L84,74 L62,83 Z", 1.0)]

# The design's adaptive layers are translate(54 54) scale(0.72) translate(-50 -51) on the 108dp canvas.
# At 0.72 two of the map's corners sit 33.6dp from the centre, past the 33dp safe circle, and a
# round launcher clipped them (seen on the emulator). 0.66 keeps every corner within 30.8dp; the
# owner chose it on 2026-10-06. iOS and Play keep the design's size.
SCALE = 0.66
TX = 54 - 50 * SCALE
TY = 54 - 51 * SCALE

HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/icon/generate_icon.py - edit that, not this. -->\n'
VECTOR_OPEN = ('<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
               '    xmlns:aapt="http://schemas.android.com/aapt"\n'
               '    android:width="108dp"\n    android:height="108dp"\n'
               '    android:viewportWidth="108"\n    android:viewportHeight="108">\n')


def vpath(data, color="#FFFFFF", alpha=1.0, indent="        "):
    a = "" if alpha == 1.0 else f'\n{indent}    android:fillAlpha="{alpha}"'
    return f'{indent}<path\n{indent}    android:pathData="{data}"\n{indent}    android:fillColor="#FF{color.lstrip("#")}"{a} />\n'


def glyph_group(body):
    return (f'    <group\n        android:translateX="{TX:.4f}"\n        android:translateY="{TY:.4f}"\n'
            f'        android:scaleX="{SCALE}"\n        android:scaleY="{SCALE}">\n{body}    </group>\n')


FOREGROUND = (HEADER + VECTOR_OPEN + glyph_group(
    f'        <clip-path android:pathData="{MAP}" />\n' +
    vpath(MAP, PAPER) + "".join(vpath(c, LAND) for c in CONTINENTS) + vpath(MIDDLE_PANEL, FOLD[0], FOLD[1])
) + '</vector>\n')

MONOCHROME = (HEADER + VECTOR_OPEN + glyph_group(
    "".join(vpath(p, "#FFFFFF", a) for p, a in MONO_PANELS)
) + '</vector>\n')

BACKGROUND = (HEADER + VECTOR_OPEN +
              '    <path android:pathData="M0,0h108v108h-108z">\n'
              '        <aapt:attr name="android:fillColor">\n'
              '            <gradient\n'
              f'                android:startX="{0.37 * 108:.2f}" android:startY="0"\n'
              f'                android:endX="{0.63 * 108:.2f}" android:endY="108"\n'
              '                android:type="linear">\n'
              f'                <item android:offset="0" android:color="#FF{GRADIENT[0].lstrip("#")}" />\n'
              f'                <item android:offset="1" android:color="#FF{GRADIENT[1].lstrip("#")}" />\n'
              '            </gradient>\n        </aapt:attr>\n    </path>\n</vector>\n')

ADAPTIVE = ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')

# --- SVGs for the PNGs ----------------------------------------------------------------------------

GRADIENT_DEF = (f'<linearGradient id="bg" x1="0.37" y1="0" x2="0.63" y2="1"><stop offset="0" stop-color="{GRADIENT[0]}"/>'
                f'<stop offset="1" stop-color="{GRADIENT[1]}"/></linearGradient>')
GLYPH_SVG = (f'<clipPath id="map"><path d="{MAP}"/></clipPath><g clip-path="url(#map)">'
             f'<path d="{MAP}" fill="{PAPER}"/>' + "".join(f'<path d="{c}" fill="{LAND}"/>' for c in CONTINENTS) +
             f'<path d="{MIDDLE_PANEL}" fill="{FOLD[0]}" fill-opacity="{FOLD[1]}"/></g>')


def square_svg():
    """The design's 3a-full-512 without its rounded corners: iOS and Play cut their own."""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs>{GRADIENT_DEF}</defs>'
            f'<rect width="100" height="100" fill="url(#bg)"/>{GLYPH_SVG}</svg>')


def legacy_svg():
    """Android 7: no mask from the launcher, so the shape is part of the image (keyline 44 of 48)."""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="-4.545 -4.545 109.09 109.09"><defs>{GRADIENT_DEF}</defs>'
            f'<rect width="100" height="100" rx="22.4" fill="url(#bg)"/>{GLYPH_SVG}</svg>')


def legacy_round_svg():
    """The adaptive icon as a circle launcher shows it: the 72dp visible part of the 108dp layers."""
    glyph = f'<g transform="translate({TX:.4f} {TY:.4f}) scale({SCALE})">{GLYPH_SVG}</g>'
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72"><defs>'
            f'<linearGradient id="bg" gradientUnits="userSpaceOnUse" x1="{0.37 * 108:.2f}" y1="0" x2="{0.63 * 108:.2f}" y2="108">'
            f'<stop offset="0" stop-color="{GRADIENT[0]}"/><stop offset="1" stop-color="{GRADIENT[1]}"/></linearGradient></defs>'
            f'<circle cx="54" cy="54" r="36" fill="url(#bg)"/>{glyph}</svg>')


def render(svg, size, out, opaque=False):
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "icon.svg")
        with open(src, "w") as f:
            f.write(svg)
        subprocess.run(["qlmanage", "-t", "-s", str(max(size, 512)), "-o", tmp, src],
                       check=True, capture_output=True)
        png = src + ".png"
        subprocess.run(["sips", "-z", str(size), str(size), png], check=True, capture_output=True)
        if opaque:
            jpg = os.path.join(tmp, "flat.jpg")
            subprocess.run(["sips", "-s", "format", "jpeg", "-s", "formatOptions", "100", png, "--out", jpg],
                           check=True, capture_output=True)
            subprocess.run(["sips", "-s", "format", "png", jpg, "--out", png], check=True, capture_output=True)
        shutil.copyfile(png, out)


def write(rel, text):
    with open(os.path.join(ROOT, rel), "w") as f:
        f.write(text)


def main():
    write("composeApp/src/androidMain/res/drawable-v24/ic_launcher_foreground.xml", FOREGROUND)
    write("composeApp/src/androidMain/res/drawable/ic_launcher_background.xml", BACKGROUND)
    write("composeApp/src/androidMain/res/drawable/ic_launcher_monochrome.xml", MONOCHROME)
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        write(f"composeApp/src/androidMain/res/mipmap-anydpi-v26/{name}", ADAPTIVE)
    for density, px in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        render(legacy_svg(), px, os.path.join(RES, f"mipmap-{density}", "ic_launcher.png"))
        render(legacy_round_svg(), px, os.path.join(RES, f"mipmap-{density}", "ic_launcher_round.png"))
    render(square_svg(), 1024, os.path.join(ROOT, "iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png"), opaque=True)
    render(square_svg(), 512, os.path.join(ROOT, "docs/icon-512.png"), opaque=True)
    print(f"3a: foreground scale {SCALE}, translate ({TX:.2f}, {TY:.2f})dp")


if __name__ == "__main__":
    main()
